name: Deploy to Server

on:
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Github Action' 
        uses: actions/checkout@master
        
      - name: executando comandos ssh remotos usando chave ssh
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd /var/opt/commands
            ./SitesUpdate.sh

